from .metrics import (
    # from CM
    calculate_accuracy_from_cm,
    calculate_recall_from_cm,
    calculate_precision_from_cm,
    calculate_specificity_from_cm,
    calculate_fpr_from_cm,
    calculate_fnr_from_cm,
    calculate_f1_beta_score_from_cm,
    calculate_f1_score_from_cm,
    calculate_balanced_accuracy_from_cm,
    calculate_mcc_from_cm,
    calculate_recall_given_minimum_specificity_from_cm,
    calculate_specificity_given_minimum_recall_from_cm,
    calculate_adjusted_f1_from_cm,
    return_tp_from_cm,
    return_tn_from_cm,
    return_fp_from_cm,
    return_fn_from_cm,
    return_cases_from_cm,
    return_non_cases_from_cm,
    return_prevalence_cases_from_cm,
    return_prevalence_non_cases_from_cm,

    # from array
    calculate_accuracy_from_array,
    calculate_true_positives_from_array,
    calculate_false_positives_from_array,
    calculate_false_negatives_from_array,
    calculate_true_negatives_from_array,
    calculate_recall_from_array,
    calculate_precision_from_array,
    calculate_specificity_from_array,
    calculate_fpr_from_array,
    calculate_fnr_from_array,
    calculate_fbeta_score_from_array,
    calculate_f1_score_from_array,
    calculate_kappa_multi_from_array,
    calculate_adjusted_f1_from_array,
    calculate_balanced_accuracy_from_array,
    calculate_mcc_from_array,
    calculate_recall_given_minimum_specificity_from_array,
    calculate_specificity_given_minimum_recall_from_array,
    calulate_roc_auc_score,
    calculate_aucpr,
    calculate_recall_given_minimum_specificity_wrapper,
    calculate_f1_given_minimum_specificity_wrapper
)

__all__ = [
    'assign_confusion_matrix_group',
    'is_float',
    'print_dict',
    'print_ndarray_summary',
    'decimal_places',
    'perform_anova',
    'perform_chi2_test',
    'format_binary_series',
    'format_continuous_series'
]

# Define the dictionary with adjusted keys and function objects as values
metrics_dict_cm = {
    'true_positives': return_tp_from_cm,
    'true_negatives': return_tn_from_cm,
    'false_positives': return_fp_from_cm,
    'false_negatives': return_fn_from_cm,
    'accuracy': calculate_accuracy_from_cm,
    'recall': calculate_recall_from_cm,
    'precision': calculate_precision_from_cm,
    'specificity': calculate_specificity_from_cm,
    'false_positive_rate': calculate_fpr_from_cm,
    'false_negative_rate': calculate_fnr_from_cm,
    'f1_score': calculate_f1_score_from_cm,
    'f1_beta_score': calculate_f1_beta_score_from_cm,
    'adjusted_f1_score': calculate_adjusted_f1_from_cm,
    'balanced_accuracy': calculate_balanced_accuracy_from_cm,
    'mcc': calculate_mcc_from_cm,
    'recall_min_spe': calculate_recall_given_minimum_specificity_from_cm,
    'spe_min_recall': calculate_specificity_given_minimum_recall_from_cm,
    'n_cases': return_cases_from_cm,
    'n_non_cases': return_non_cases_from_cm,
    'prev_cases': return_prevalence_cases_from_cm,
    'prev_non_cases': return_prevalence_non_cases_from_cm
}

metrics_dict_array = {
    'accuracy': calculate_accuracy_from_array,
    'true_positives': calculate_true_positives_from_array,
    'false_positives': calculate_false_positives_from_array,
    'false_negatives': calculate_false_negatives_from_array,
    'true_negatives': calculate_true_negatives_from_array,
    'recall': calculate_recall_from_array,
    'precision': calculate_precision_from_array,
    'specificity': calculate_specificity_from_array,
    'false_positive_rate': calculate_fpr_from_array,
    'false_negative_rate': calculate_fnr_from_array,
    'fbeta_score': calculate_fbeta_score_from_array,
    'f1_score': calculate_f1_score_from_array,
    'kappa': calculate_kappa_multi_from_array,
    'adjusted_f1_score': calculate_adjusted_f1_from_array,
    'balanced_accuracy': calculate_balanced_accuracy_from_array,
    'mcc': calculate_mcc_from_array,
    'recall_min_spe': calculate_recall_given_minimum_specificity_from_array,
    'recall_min_spe_wrapper': calculate_recall_given_minimum_specificity_wrapper,
    'f1_min_spe_wrapper': calculate_f1_given_minimum_specificity_wrapper,
    'spe_min_recall': calculate_specificity_given_minimum_recall_from_array,
    'aucroc': calulate_roc_auc_score,
    'aucpr': calculate_aucpr
}

